// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHwHZqM1Fme81xP8fNKPuMsz-jPjAF6bw',
    appId: '1:99906396548:web:a30b6cbee9ab4ddcd77dd1',
    messagingSenderId: '99906396548',
    projectId: 'instagramclone-d7c16',
    authDomain: 'instagramclone-d7c16.firebaseapp.com',
    storageBucket: 'instagramclone-d7c16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoddkSzBgWE3Tz6p28mN8sh0gF-SkZ8lI',
    appId: '1:99906396548:android:8550db59502da615d77dd1',
    messagingSenderId: '99906396548',
    projectId: 'instagramclone-d7c16',
    storageBucket: 'instagramclone-d7c16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIR6pqfGWxXNmNX9ur1ljC5fRvAHB3g64',
    appId: '1:99906396548:ios:1961cc0818c54f31d77dd1',
    messagingSenderId: '99906396548',
    projectId: 'instagramclone-d7c16',
    storageBucket: 'instagramclone-d7c16.firebasestorage.app',
    iosBundleId: 'com.example.insgramClone',
  );
}
